DROP TABLE IF EXISTS VOTE;

CREATE TABLE VOTE (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  COUNTRY_FROM VARCHAR(20) NOT NULL,
  VOTED_FOR VARCHAR(20) NOT NULL,
  VOTING_YEAR VARCHAR(5) NOT NULL
);

create index vote_year_index on VOTE(VOTING_YEAR);

create index votedfor_year_index on VOTE(VOTING_YEAR, VOTED_FOR);