DROP TABLE IF EXISTS VOTE;

CREATE TABLE VOTE (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  COUNTRY_FROM VARCHAR(20) NOT NULL,
  VOTED_FOR VARCHAR(20) NOT NULL,
  VOTING_YEAR VARCHAR(5) NOT NULL
);

create index votingyear_index on VOTE(VOTING_YEAR);

create index year_countryfrom_index on VOTE(VOTING_YEAR, COUNTRY_FROM);